### ISSUE TITLE
Can't login using the meross integration

### ISSUE THREAD

**Issue by TheBinaryLoop** [albertogeniola/ha-meross-local-broker#2] opened 2022-05-31 19:46 UTC
![image](https://user-images.githubusercontent.com/13447164/171272211-b22f0be6-af05-474c-8871-dee4785b495f.png)

**Comment by albertogeniola** [comment] 2022-06-18 14:44
Solved with latest versions of the integration and local addon. Please update and let me know if that's now working as intended.

**Comment by albertogeniola** [comment] 2022-06-23 16:37
I am closing this as no further info was provided. Feel free to reopen if needed.

**Closed by albertogeniola** 2022-06-23 16:37 UTC
Labels: bug, waiting validation
